### ISSUE TITLE
Jumpy scrolling behaviour in comments

### ISSUE THREAD

**Issue by novedevo** [msfjarvis/compose-lobsters#584] opened 2024-06-07 17:51 UTC
When scrolling back up to the top of a comments section (specifically, when the page is still moving from the inertia of a previous swipe - there's no jumping when your finger is touching the screen), the movement isn't smooth as expected, but jumps in an unexpected way. I don't see this behaviour in other apps, although I'm not sure if I have any other Jetpack Compose apps with scrolling. 

Video here - note especially the jumpiness of the last scroll-up:

https://photos.app.goo.gl/Y53AHT8M9yBe2Dvj6

I'm using a Pixel 8 Pro with stock Android 14 and the latest (May) security updates, Claw 1.48.0 (although I also saw this on 1.47.0, and maybe earlier). Installed from F-droid. Happy to provide any other information you need.

Thank you for making this app! It's the best lobste.rs client, and this is just a minor annoyance.

**Comment by msfjarvis** [comment] 2024-06-07 17:57
That's disappointing, I thought this was finally gone with the new release :(

I'm currently working on a big refactor to fix a bunch of stuff (including the root cause of #558) but I'll try to ensure I fix this for the next release as well.

**Comment by msfjarvis** [comment] 2024-08-20 20:02
Closed this a bit pre-emptively, issue is less pronounced but still there.

**Comment by msfjarvis** [comment] 2024-08-29 15:46
I think this is completely fixed now

**Closed** 2024-08-29 15:46 UTC
Labels: bug, good first issue
